export const SAVE_HOME_DATA = "SAVE_HOME_DATA";
export const FETCH_HOME_DATA = "FETCH_HOME_DATA";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SAVE_SEARCH_RESULTS = "SAVE_SEARCH_RESULTS";
export const START_LOADING="START_LOADING";
export const STOP_LOADING="STOP_LOADING";

